### ISSUE TITLE
Investments history

### ISSUE THREAD

**Issue by anonrootkit** [anonrootkit/wrx-ticker#12]
Thinking to add investments history, where users can see their investments history with complete data (purchased coins, time, etc).

What say? @snifhex @vocuzi

**Comment by snifhex** [comment]
@anonrootkit are we thinking about showing this history as individual transactions or can we group/cluster transactions of same currency?

-> Like user clicks on a currency like "MANA" in history he/she will be shown all the transactions related to MANA,.
-> Do we need to divide these transactions further ? In two categories i.e. bought and sold.

**Comment by anonrootkit** [comment]
Resolution : History screen added and user can add their sell orders their, hence closing this issue.
