### ISSUE TITLE
Let user delete/remove existing investments/coins

### ISSUE THREAD

**Issue by anonrootkit** [anonrootkit/wrx-ticker#9]
Let user delete/remove existing investments/coins or mark investments as sold or something. Need discussion. @snifhex @vocuzi

**Comment by anonrootkit** [comment]
Updated description: Let user remove his investments or coins from the list.

**Comment by anonrootkit** [comment]
Update : Branch associated : [remove-coins](https://github.com/anonrootkit/wrx-ticker/tree/remove-coins)

**Comment by snifhex** [comment]
I'm available at 2pm IST for discussion.

**Comment by anonrootkit** [comment]
Update : PR #11

**Comment by anonrootkit** [comment]
Resolution: PR has been merged, hence closing this issue.
